from __future__ import annotations

import re
import tomllib
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
_NAME_PATTERN = re.compile(r"^[A-Za-z0-9_.-]+")


def _normalize_name(name: str) -> str:
    return re.sub(r"[-_.]+", "-", name).lower()


def _requirement_name(requirement: str) -> str:
    match = _NAME_PATTERN.match(requirement.strip())
    assert match is not None, f"Unable to parse requirement: {requirement}"
    return _normalize_name(match.group())


def _input_names(path: Path) -> set[str]:
    names: set[str] = set()
    for raw_line in path.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if line and not line.startswith(("#", "-")):
            names.add(_requirement_name(line))
    return names


def _lock_pins(path: Path) -> dict[str, str]:
    pins: dict[str, str] = {}
    for raw_line in path.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or line.startswith(("#", "-")):
            continue
        name, separator, version = line.partition("==")
        assert separator and version, f"Unpinned lock entry in {path.name}: {line}"
        pins[_normalize_name(name)] = version
    return pins


def test_requirement_inputs_match_project_dependency_groups() -> None:
    project = tomllib.loads((ROOT / "pyproject.toml").read_text(encoding="utf-8"))["project"]
    production_names = {_requirement_name(item) for item in project["dependencies"]}
    dev_names = {_requirement_name(item) for item in project["optional-dependencies"]["dev"]}

    assert _input_names(ROOT / "requirements.in") == production_names
    assert _input_names(ROOT / "requirements-dev.in") == dev_names


def test_development_lock_contains_identical_production_pins() -> None:
    production_pins = _lock_pins(ROOT / "requirements.lock")
    development_pins = _lock_pins(ROOT / "requirements-dev.lock")

    assert production_pins
    assert production_pins.items() <= development_pins.items()


def test_locks_are_generated_with_supported_python_version() -> None:
    expected_header = "autogenerated by pip-compile with Python 3.12"

    assert expected_header in (ROOT / "requirements.lock").read_text(encoding="utf-8")
    assert expected_header in (ROOT / "requirements-dev.lock").read_text(encoding="utf-8")
